# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

inherit node-bundled
MYPN="rollup"
SRC_URI="
https://github.com/rollup/rollup/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz

mirror://npm/@babel/code-frame/-/code-frame-7.12.13.tgz
mirror://npm/@babel/core/-/core-7.12.16.tgz
mirror://npm/json5/-/json5-2.2.0.tgz
mirror://npm/semver/-/semver-5.7.1.tgz
mirror://npm/source-map/-/source-map-0.5.7.tgz
mirror://npm/@babel/generator/-/generator-7.12.15.tgz
mirror://npm/jsesc/-/jsesc-2.5.2.tgz
mirror://npm/source-map/-/source-map-0.5.7.tgz
mirror://npm/@babel/helper-function-name/-/helper-function-name-7.12.13.tgz
mirror://npm/@babel/helper-get-function-arity/-/helper-get-function-arity-7.12.13.tgz
mirror://npm/@babel/helper-member-expression-to-functions/-/helper-member-expression-to-functions-7.12.16.tgz
mirror://npm/@babel/helper-module-imports/-/helper-module-imports-7.12.13.tgz
mirror://npm/@babel/helper-module-transforms/-/helper-module-transforms-7.12.13.tgz
mirror://npm/@babel/helper-optimise-call-expression/-/helper-optimise-call-expression-7.12.13.tgz
mirror://npm/@babel/helper-replace-supers/-/helper-replace-supers-7.12.13.tgz
mirror://npm/@babel/helper-simple-access/-/helper-simple-access-7.12.13.tgz
mirror://npm/@babel/helper-split-export-declaration/-/helper-split-export-declaration-7.12.13.tgz
mirror://npm/@babel/helper-validator-identifier/-/helper-validator-identifier-7.12.11.tgz
mirror://npm/@babel/helpers/-/helpers-7.12.13.tgz
mirror://npm/@babel/highlight/-/highlight-7.12.13.tgz
mirror://npm/@babel/parser/-/parser-7.12.16.tgz
mirror://npm/@babel/template/-/template-7.12.13.tgz
mirror://npm/@babel/traverse/-/traverse-7.12.13.tgz
mirror://npm/globals/-/globals-11.12.0.tgz
mirror://npm/@babel/types/-/types-7.12.13.tgz
mirror://npm/@eslint/eslintrc/-/eslintrc-0.3.0.tgz
mirror://npm/@istanbuljs/load-nyc-config/-/load-nyc-config-1.1.0.tgz
mirror://npm/camelcase/-/camelcase-5.3.1.tgz
mirror://npm/find-up/-/find-up-4.1.0.tgz
mirror://npm/locate-path/-/locate-path-5.0.0.tgz
mirror://npm/p-limit/-/p-limit-2.3.0.tgz
mirror://npm/p-locate/-/p-locate-4.1.0.tgz
mirror://npm/p-try/-/p-try-2.2.0.tgz
mirror://npm/path-exists/-/path-exists-4.0.0.tgz
mirror://npm/resolve-from/-/resolve-from-5.0.0.tgz
mirror://npm/@istanbuljs/schema/-/schema-0.1.2.tgz
mirror://npm/@rollup/plugin-alias/-/plugin-alias-3.1.2.tgz
mirror://npm/@rollup/plugin-buble/-/plugin-buble-0.21.3.tgz
mirror://npm/@rollup/plugin-commonjs/-/plugin-commonjs-18.0.0-1.tgz
mirror://npm/estree-walker/-/estree-walker-2.0.2.tgz
mirror://npm/is-reference/-/is-reference-1.2.1.tgz
mirror://npm/@rollup/plugin-json/-/plugin-json-4.1.0.tgz
mirror://npm/@rollup/plugin-node-resolve/-/plugin-node-resolve-11.1.1.tgz
mirror://npm/@rollup/plugin-replace/-/plugin-replace-2.3.4.tgz
mirror://npm/@rollup/pluginutils/-/pluginutils-3.1.0.tgz
mirror://npm/@tootallnate/once/-/once-1.1.2.tgz
mirror://npm/@types/braces/-/braces-3.0.0.tgz
mirror://npm/@types/buble/-/buble-0.19.2.tgz
mirror://npm/@types/estree/-/estree-0.0.39.tgz
mirror://npm/@types/fs-extra/-/fs-extra-8.1.1.tgz
mirror://npm/@types/glob/-/glob-7.1.3.tgz
mirror://npm/@types/json5/-/json5-0.0.29.tgz
mirror://npm/@types/micromatch/-/micromatch-4.0.1.tgz
mirror://npm/@types/minimatch/-/minimatch-3.0.3.tgz
mirror://npm/@types/node/-/node-10.17.51.tgz
mirror://npm/@types/parse-json/-/parse-json-4.0.0.tgz
mirror://npm/@types/require-relative/-/require-relative-0.8.0.tgz
mirror://npm/@types/resolve/-/resolve-1.17.1.tgz
mirror://npm/@types/rimraf/-/rimraf-2.0.4.tgz
mirror://npm/@types/signal-exit/-/signal-exit-3.0.0.tgz
mirror://npm/@types/yargs-parser/-/yargs-parser-20.2.0.tgz
mirror://npm/@ungap/promise-all-settled/-/promise-all-settled-1.1.2.tgz
mirror://npm/acorn/-/acorn-8.0.5.tgz
mirror://npm/acorn-class-fields/-/acorn-class-fields-1.0.0.tgz
mirror://npm/acorn-dynamic-import/-/acorn-dynamic-import-4.0.0.tgz
mirror://npm/acorn-jsx/-/acorn-jsx-5.3.1.tgz
mirror://npm/acorn-private-class-elements/-/acorn-private-class-elements-1.0.0.tgz
mirror://npm/acorn-static-class-features/-/acorn-static-class-features-1.0.0.tgz
mirror://npm/acorn-walk/-/acorn-walk-8.0.2.tgz
mirror://npm/agent-base/-/agent-base-6.0.2.tgz
mirror://npm/aggregate-error/-/aggregate-error-3.1.0.tgz
mirror://npm/ajv/-/ajv-6.12.6.tgz
mirror://npm/ansi-colors/-/ansi-colors-4.1.1.tgz
mirror://npm/ansi-escapes/-/ansi-escapes-4.3.1.tgz
mirror://npm/type-fest/-/type-fest-0.11.0.tgz
mirror://npm/ansi-regex/-/ansi-regex-5.0.0.tgz
mirror://npm/ansi-styles/-/ansi-styles-3.2.1.tgz
mirror://npm/anymatch/-/anymatch-3.1.1.tgz
mirror://npm/append-transform/-/append-transform-2.0.0.tgz
mirror://npm/archy/-/archy-1.0.0.tgz
mirror://npm/argparse/-/argparse-1.0.10.tgz
mirror://npm/argv/-/argv-0.0.2.tgz
mirror://npm/array-find-index/-/array-find-index-1.0.2.tgz
mirror://npm/array-includes/-/array-includes-3.1.2.tgz
mirror://npm/array.prototype.flat/-/array.prototype.flat-1.2.4.tgz
mirror://npm/astral-regex/-/astral-regex-2.0.0.tgz
mirror://npm/balanced-match/-/balanced-match-1.0.0.tgz
mirror://npm/binary-extensions/-/binary-extensions-2.2.0.tgz
mirror://npm/brace-expansion/-/brace-expansion-1.1.11.tgz
mirror://npm/braces/-/braces-3.0.2.tgz
mirror://npm/browser-stdout/-/browser-stdout-1.3.1.tgz
mirror://npm/buble/-/buble-0.20.0.tgz
mirror://npm/acorn/-/acorn-6.4.2.tgz
mirror://npm/buffer-from/-/buffer-from-1.1.1.tgz
mirror://npm/builtin-modules/-/builtin-modules-3.2.0.tgz
mirror://npm/caching-transform/-/caching-transform-4.0.0.tgz
mirror://npm/call-bind/-/call-bind-1.0.2.tgz
mirror://npm/callsites/-/callsites-3.1.0.tgz
mirror://npm/camelcase/-/camelcase-6.2.0.tgz
mirror://npm/chalk/-/chalk-2.4.2.tgz
mirror://npm/chokidar/-/chokidar-3.5.1.tgz
mirror://npm/clean-stack/-/clean-stack-2.2.0.tgz
mirror://npm/cli-cursor/-/cli-cursor-3.1.0.tgz
mirror://npm/cli-truncate/-/cli-truncate-2.1.0.tgz
mirror://npm/ansi-styles/-/ansi-styles-4.3.0.tgz
mirror://npm/color-convert/-/color-convert-2.0.1.tgz
mirror://npm/color-name/-/color-name-1.1.4.tgz
mirror://npm/slice-ansi/-/slice-ansi-3.0.0.tgz
mirror://npm/cliui/-/cliui-7.0.4.tgz
mirror://npm/codecov/-/codecov-3.8.1.tgz
mirror://npm/color-convert/-/color-convert-1.9.3.tgz
mirror://npm/color-name/-/color-name-1.1.3.tgz
mirror://npm/colorette/-/colorette-1.2.1.tgz
mirror://npm/commander/-/commander-6.2.1.tgz
mirror://npm/commenting/-/commenting-1.1.0.tgz
mirror://npm/commondir/-/commondir-1.0.1.tgz
mirror://npm/concat-map/-/concat-map-0.0.1.tgz
mirror://npm/contains-path/-/contains-path-0.1.0.tgz
mirror://npm/convert-source-map/-/convert-source-map-1.7.0.tgz
mirror://npm/safe-buffer/-/safe-buffer-5.1.2.tgz
mirror://npm/core-js/-/core-js-3.8.3.tgz
mirror://npm/cosmiconfig/-/cosmiconfig-7.0.0.tgz
mirror://npm/parse-json/-/parse-json-5.2.0.tgz
mirror://npm/path-type/-/path-type-4.0.0.tgz
mirror://npm/cross-spawn/-/cross-spawn-7.0.3.tgz
mirror://npm/date-time/-/date-time-3.1.0.tgz
mirror://npm/debug/-/debug-4.3.1.tgz
mirror://npm/decamelize/-/decamelize-4.0.0.tgz
mirror://npm/dedent/-/dedent-0.7.0.tgz
mirror://npm/deep-extend/-/deep-extend-0.6.0.tgz
mirror://npm/deep-is/-/deep-is-0.1.3.tgz
mirror://npm/deepmerge/-/deepmerge-4.2.2.tgz
mirror://npm/default-require-extensions/-/default-require-extensions-3.0.0.tgz
mirror://npm/strip-bom/-/strip-bom-4.0.0.tgz
mirror://npm/define-properties/-/define-properties-1.1.3.tgz
mirror://npm/detect-indent/-/detect-indent-6.0.0.tgz
mirror://npm/diff/-/diff-5.0.0.tgz
mirror://npm/doctrine/-/doctrine-3.0.0.tgz
mirror://npm/emoji-regex/-/emoji-regex-8.0.0.tgz
mirror://npm/end-of-stream/-/end-of-stream-1.4.4.tgz
mirror://npm/enquirer/-/enquirer-2.3.6.tgz
mirror://npm/ensure-posix-path/-/ensure-posix-path-1.1.1.tgz
mirror://npm/entities/-/entities-2.0.3.tgz
mirror://npm/error-ex/-/error-ex-1.3.2.tgz
mirror://npm/es-abstract/-/es-abstract-1.18.0-next.2.tgz
mirror://npm/es-to-primitive/-/es-to-primitive-1.2.1.tgz
mirror://npm/es5-shim/-/es5-shim-4.5.15.tgz
mirror://npm/es6-error/-/es6-error-4.1.1.tgz
mirror://npm/es6-shim/-/es6-shim-0.35.6.tgz
mirror://npm/escalade/-/escalade-3.1.1.tgz
mirror://npm/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz
mirror://npm/eslint/-/eslint-7.19.0.tgz
mirror://npm/ansi-styles/-/ansi-styles-4.3.0.tgz
mirror://npm/chalk/-/chalk-4.1.0.tgz
mirror://npm/color-convert/-/color-convert-2.0.1.tgz
mirror://npm/color-name/-/color-name-1.1.4.tgz
mirror://npm/has-flag/-/has-flag-4.0.0.tgz
mirror://npm/supports-color/-/supports-color-7.2.0.tgz
mirror://npm/eslint-import-resolver-node/-/eslint-import-resolver-node-0.3.4.tgz
mirror://npm/debug/-/debug-2.6.9.tgz
mirror://npm/ms/-/ms-2.0.0.tgz
mirror://npm/eslint-module-utils/-/eslint-module-utils-2.6.0.tgz
mirror://npm/debug/-/debug-2.6.9.tgz
mirror://npm/ms/-/ms-2.0.0.tgz
mirror://npm/eslint-plugin-import/-/eslint-plugin-import-2.22.1.tgz
mirror://npm/debug/-/debug-2.6.9.tgz
mirror://npm/doctrine/-/doctrine-1.5.0.tgz
mirror://npm/ms/-/ms-2.0.0.tgz
mirror://npm/eslint-scope/-/eslint-scope-5.1.1.tgz
mirror://npm/eslint-utils/-/eslint-utils-2.1.0.tgz
mirror://npm/eslint-visitor-keys/-/eslint-visitor-keys-1.3.0.tgz
mirror://npm/eslint-visitor-keys/-/eslint-visitor-keys-2.0.0.tgz
mirror://npm/espree/-/espree-7.3.1.tgz
mirror://npm/acorn/-/acorn-7.4.1.tgz
mirror://npm/eslint-visitor-keys/-/eslint-visitor-keys-1.3.0.tgz
mirror://npm/esprima/-/esprima-4.0.1.tgz
mirror://npm/esquery/-/esquery-1.4.0.tgz
mirror://npm/estraverse/-/estraverse-5.2.0.tgz
mirror://npm/esrecurse/-/esrecurse-4.3.0.tgz
mirror://npm/estraverse/-/estraverse-5.2.0.tgz
mirror://npm/estraverse/-/estraverse-4.3.0.tgz
mirror://npm/estree-walker/-/estree-walker-1.0.1.tgz
mirror://npm/esutils/-/esutils-2.0.3.tgz
mirror://npm/execa/-/execa-5.0.0.tgz
mirror://npm/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz
mirror://npm/fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz
mirror://npm/fast-levenshtein/-/fast-levenshtein-2.0.6.tgz
mirror://npm/figures/-/figures-3.2.0.tgz
mirror://npm/file-entry-cache/-/file-entry-cache-6.0.0.tgz
mirror://npm/fill-range/-/fill-range-7.0.1.tgz
mirror://npm/find-cache-dir/-/find-cache-dir-3.3.1.tgz
mirror://npm/find-up/-/find-up-4.1.0.tgz
mirror://npm/locate-path/-/locate-path-5.0.0.tgz
mirror://npm/p-limit/-/p-limit-2.3.0.tgz
mirror://npm/p-locate/-/p-locate-4.1.0.tgz
mirror://npm/p-try/-/p-try-2.2.0.tgz
mirror://npm/path-exists/-/path-exists-4.0.0.tgz
mirror://npm/pkg-dir/-/pkg-dir-4.2.0.tgz
mirror://npm/find-up/-/find-up-2.1.0.tgz
mirror://npm/fixturify/-/fixturify-2.1.0.tgz
mirror://npm/flat/-/flat-5.0.2.tgz
mirror://npm/flat-cache/-/flat-cache-3.0.4.tgz
mirror://npm/flatted/-/flatted-3.1.1.tgz
mirror://npm/foreground-child/-/foreground-child-2.0.0.tgz
mirror://npm/fromentries/-/fromentries-1.3.2.tgz
mirror://npm/fs-extra/-/fs-extra-8.1.0.tgz
mirror://npm/fs.realpath/-/fs.realpath-1.0.0.tgz
mirror://npm/fsevents/-/fsevents-2.3.2.tgz
mirror://npm/function-bind/-/function-bind-1.1.1.tgz
mirror://npm/functional-red-black-tree/-/functional-red-black-tree-1.0.1.tgz
mirror://npm/gensync/-/gensync-1.0.0-beta.2.tgz
mirror://npm/get-caller-file/-/get-caller-file-2.0.5.tgz
mirror://npm/get-intrinsic/-/get-intrinsic-1.1.1.tgz
mirror://npm/get-own-enumerable-property-symbols/-/get-own-enumerable-property-symbols-3.0.2.tgz
mirror://npm/get-package-type/-/get-package-type-0.1.0.tgz
mirror://npm/get-stdin/-/get-stdin-8.0.0.tgz
mirror://npm/get-stream/-/get-stream-6.0.0.tgz
mirror://npm/get-symbol-from-current-process-h/-/get-symbol-from-current-process-h-1.0.2.tgz
mirror://npm/get-uv-event-loop-napi-h/-/get-uv-event-loop-napi-h-1.0.6.tgz
mirror://npm/glob/-/glob-7.1.6.tgz
mirror://npm/glob-parent/-/glob-parent-5.1.1.tgz
mirror://npm/globals/-/globals-12.4.0.tgz
mirror://npm/graceful-fs/-/graceful-fs-4.2.6.tgz
mirror://npm/growl/-/growl-1.10.5.tgz
mirror://npm/has/-/has-1.0.3.tgz
mirror://npm/has-flag/-/has-flag-3.0.0.tgz
mirror://npm/has-symbols/-/has-symbols-1.0.1.tgz
mirror://npm/hash.js/-/hash.js-1.1.7.tgz
mirror://npm/hasha/-/hasha-5.2.2.tgz
mirror://npm/he/-/he-1.2.0.tgz
mirror://npm/hosted-git-info/-/hosted-git-info-2.8.8.tgz
mirror://npm/html-escaper/-/html-escaper-2.0.2.tgz
mirror://npm/http-proxy-agent/-/http-proxy-agent-4.0.1.tgz
mirror://npm/https-proxy-agent/-/https-proxy-agent-4.0.0.tgz
mirror://npm/agent-base/-/agent-base-5.1.1.tgz
mirror://npm/human-signals/-/human-signals-2.1.0.tgz
mirror://npm/husky/-/husky-5.0.9.tgz
mirror://npm/ignore/-/ignore-4.0.6.tgz
mirror://npm/ignore-walk/-/ignore-walk-3.0.3.tgz
mirror://npm/import-fresh/-/import-fresh-3.3.0.tgz
mirror://npm/imurmurhash/-/imurmurhash-0.1.4.tgz
mirror://npm/indent-string/-/indent-string-4.0.0.tgz
mirror://npm/inflight/-/inflight-1.0.6.tgz
mirror://npm/inherits/-/inherits-2.0.4.tgz
mirror://npm/ini/-/ini-1.3.8.tgz
mirror://npm/interpret/-/interpret-1.4.0.tgz
mirror://npm/is-arrayish/-/is-arrayish-0.2.1.tgz
mirror://npm/is-binary-path/-/is-binary-path-2.1.0.tgz
mirror://npm/is-callable/-/is-callable-1.2.3.tgz
mirror://npm/is-core-module/-/is-core-module-2.2.0.tgz
mirror://npm/is-date-object/-/is-date-object-1.0.2.tgz
mirror://npm/is-extglob/-/is-extglob-2.1.1.tgz
mirror://npm/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz
mirror://npm/is-glob/-/is-glob-4.0.1.tgz
mirror://npm/is-module/-/is-module-1.0.0.tgz
mirror://npm/is-negative-zero/-/is-negative-zero-2.0.1.tgz
mirror://npm/is-number/-/is-number-7.0.0.tgz
mirror://npm/is-obj/-/is-obj-1.0.1.tgz
mirror://npm/is-plain-obj/-/is-plain-obj-2.1.0.tgz
mirror://npm/is-regex/-/is-regex-1.1.2.tgz
mirror://npm/is-regexp/-/is-regexp-1.0.0.tgz
mirror://npm/is-stream/-/is-stream-2.0.0.tgz
mirror://npm/is-string/-/is-string-1.0.5.tgz
mirror://npm/is-symbol/-/is-symbol-1.0.3.tgz
mirror://npm/is-typedarray/-/is-typedarray-1.0.0.tgz
mirror://npm/is-windows/-/is-windows-1.0.2.tgz
mirror://npm/isarray/-/isarray-1.0.0.tgz
mirror://npm/isexe/-/isexe-2.0.0.tgz
mirror://npm/istanbul-lib-coverage/-/istanbul-lib-coverage-3.0.0.tgz
mirror://npm/istanbul-lib-hook/-/istanbul-lib-hook-3.0.0.tgz
mirror://npm/istanbul-lib-instrument/-/istanbul-lib-instrument-4.0.3.tgz
mirror://npm/semver/-/semver-6.3.0.tgz
mirror://npm/istanbul-lib-processinfo/-/istanbul-lib-processinfo-2.0.2.tgz
mirror://npm/p-map/-/p-map-3.0.0.tgz
mirror://npm/istanbul-lib-report/-/istanbul-lib-report-3.0.0.tgz
mirror://npm/has-flag/-/has-flag-4.0.0.tgz
mirror://npm/supports-color/-/supports-color-7.2.0.tgz
mirror://npm/istanbul-lib-source-maps/-/istanbul-lib-source-maps-4.0.0.tgz
mirror://npm/source-map/-/source-map-0.6.1.tgz
mirror://npm/istanbul-reports/-/istanbul-reports-3.0.2.tgz
mirror://npm/jest-worker/-/jest-worker-26.6.2.tgz
mirror://npm/has-flag/-/has-flag-4.0.0.tgz
mirror://npm/supports-color/-/supports-color-7.2.0.tgz
mirror://npm/js-tokens/-/js-tokens-4.0.0.tgz
mirror://npm/js-yaml/-/js-yaml-3.14.0.tgz
mirror://npm/jsesc/-/jsesc-0.5.0.tgz
mirror://npm/json-parse-even-better-errors/-/json-parse-even-better-errors-2.3.1.tgz
mirror://npm/json-schema-traverse/-/json-schema-traverse-0.4.1.tgz
mirror://npm/json-stable-stringify-without-jsonify/-/json-stable-stringify-without-jsonify-1.0.1.tgz
mirror://npm/json5/-/json5-1.0.1.tgz
mirror://npm/jsonc-parser/-/jsonc-parser-3.0.0.tgz
mirror://npm/jsonfile/-/jsonfile-4.0.0.tgz
mirror://npm/levn/-/levn-0.4.1.tgz
mirror://npm/lines-and-columns/-/lines-and-columns-1.1.6.tgz
mirror://npm/linkify-it/-/linkify-it-3.0.2.tgz
mirror://npm/lint-staged/-/lint-staged-10.5.4.tgz
mirror://npm/ansi-styles/-/ansi-styles-4.3.0.tgz
mirror://npm/chalk/-/chalk-4.1.0.tgz
mirror://npm/color-convert/-/color-convert-2.0.1.tgz
mirror://npm/color-name/-/color-name-1.1.4.tgz
mirror://npm/execa/-/execa-4.1.0.tgz
mirror://npm/get-stream/-/get-stream-5.2.0.tgz
mirror://npm/has-flag/-/has-flag-4.0.0.tgz
mirror://npm/human-signals/-/human-signals-1.1.1.tgz
mirror://npm/supports-color/-/supports-color-7.2.0.tgz
mirror://npm/listr2/-/listr2-3.3.1.tgz
mirror://npm/ansi-styles/-/ansi-styles-4.3.0.tgz
mirror://npm/chalk/-/chalk-4.1.0.tgz
mirror://npm/color-convert/-/color-convert-2.0.1.tgz
mirror://npm/color-name/-/color-name-1.1.4.tgz
mirror://npm/has-flag/-/has-flag-4.0.0.tgz
mirror://npm/supports-color/-/supports-color-7.2.0.tgz
mirror://npm/load-json-file/-/load-json-file-2.0.0.tgz
mirror://npm/locate-character/-/locate-character-2.0.5.tgz
mirror://npm/locate-path/-/locate-path-2.0.0.tgz
mirror://npm/lodash/-/lodash-4.17.20.tgz
mirror://npm/lodash.differencewith/-/lodash.differencewith-4.5.0.tgz
mirror://npm/lodash.flatten/-/lodash.flatten-4.4.0.tgz
mirror://npm/lodash.flattendeep/-/lodash.flattendeep-4.4.0.tgz
mirror://npm/log-symbols/-/log-symbols-4.0.0.tgz
mirror://npm/ansi-styles/-/ansi-styles-4.3.0.tgz
mirror://npm/chalk/-/chalk-4.1.0.tgz
mirror://npm/color-convert/-/color-convert-2.0.1.tgz
mirror://npm/color-name/-/color-name-1.1.4.tgz
mirror://npm/has-flag/-/has-flag-4.0.0.tgz
mirror://npm/supports-color/-/supports-color-7.2.0.tgz
mirror://npm/log-update/-/log-update-4.0.0.tgz
mirror://npm/ansi-styles/-/ansi-styles-4.3.0.tgz
mirror://npm/color-convert/-/color-convert-2.0.1.tgz
mirror://npm/color-name/-/color-name-1.1.4.tgz
mirror://npm/wrap-ansi/-/wrap-ansi-6.2.0.tgz
mirror://npm/lru-cache/-/lru-cache-6.0.0.tgz
mirror://npm/magic-string/-/magic-string-0.25.7.tgz
mirror://npm/make-dir/-/make-dir-3.1.0.tgz
mirror://npm/semver/-/semver-6.3.0.tgz
mirror://npm/markdown-it/-/markdown-it-12.0.2.tgz
mirror://npm/argparse/-/argparse-2.0.1.tgz
mirror://npm/markdownlint/-/markdownlint-0.22.0.tgz
mirror://npm/markdownlint-cli/-/markdownlint-cli-0.26.0.tgz
mirror://npm/ignore/-/ignore-5.1.8.tgz
mirror://npm/js-yaml/-/js-yaml-3.14.1.tgz
mirror://npm/markdownlint-rule-helpers/-/markdownlint-rule-helpers-0.13.0.tgz
mirror://npm/matcher-collection/-/matcher-collection-2.0.1.tgz
mirror://npm/mdurl/-/mdurl-1.0.1.tgz
mirror://npm/merge-stream/-/merge-stream-2.0.0.tgz
mirror://npm/micromatch/-/micromatch-4.0.2.tgz
mirror://npm/mimic-fn/-/mimic-fn-2.1.0.tgz
mirror://npm/minimalistic-assert/-/minimalistic-assert-1.0.1.tgz
mirror://npm/minimatch/-/minimatch-3.0.4.tgz
mirror://npm/minimist/-/minimist-1.2.5.tgz
mirror://npm/mkdirp/-/mkdirp-1.0.4.tgz
mirror://npm/mocha/-/mocha-8.3.0.tgz
mirror://npm/argparse/-/argparse-2.0.1.tgz
mirror://npm/escape-string-regexp/-/escape-string-regexp-4.0.0.tgz
mirror://npm/find-up/-/find-up-5.0.0.tgz
mirror://npm/has-flag/-/has-flag-4.0.0.tgz
mirror://npm/js-yaml/-/js-yaml-4.0.0.tgz
mirror://npm/locate-path/-/locate-path-6.0.0.tgz
mirror://npm/ms/-/ms-2.1.3.tgz
mirror://npm/p-limit/-/p-limit-3.1.0.tgz
mirror://npm/p-locate/-/p-locate-5.0.0.tgz
mirror://npm/path-exists/-/path-exists-4.0.0.tgz
mirror://npm/supports-color/-/supports-color-8.1.1.tgz
mirror://npm/moment/-/moment-2.27.0.tgz
mirror://npm/ms/-/ms-2.1.2.tgz
mirror://npm/nanoid/-/nanoid-3.1.20.tgz
mirror://npm/natural-compare/-/natural-compare-1.4.0.tgz
mirror://npm/node-addon-api/-/node-addon-api-3.1.0.tgz
mirror://npm/node-fetch/-/node-fetch-2.6.1.tgz
mirror://npm/node-gyp-build/-/node-gyp-build-4.2.3.tgz
mirror://npm/node-preload/-/node-preload-0.2.1.tgz
mirror://npm/normalize-package-data/-/normalize-package-data-2.5.0.tgz
mirror://npm/semver/-/semver-5.7.1.tgz
mirror://npm/normalize-path/-/normalize-path-3.0.0.tgz
mirror://npm/npm-run-path/-/npm-run-path-4.0.1.tgz
mirror://npm/nyc/-/nyc-15.1.0.tgz
mirror://npm/ansi-styles/-/ansi-styles-4.3.0.tgz
mirror://npm/camelcase/-/camelcase-5.3.1.tgz
mirror://npm/cliui/-/cliui-6.0.0.tgz
mirror://npm/color-convert/-/color-convert-2.0.1.tgz
mirror://npm/color-name/-/color-name-1.1.4.tgz
mirror://npm/decamelize/-/decamelize-1.2.0.tgz
mirror://npm/find-up/-/find-up-4.1.0.tgz
mirror://npm/locate-path/-/locate-path-5.0.0.tgz
mirror://npm/p-limit/-/p-limit-2.3.0.tgz
mirror://npm/p-locate/-/p-locate-4.1.0.tgz
mirror://npm/p-map/-/p-map-3.0.0.tgz
mirror://npm/p-try/-/p-try-2.2.0.tgz
mirror://npm/path-exists/-/path-exists-4.0.0.tgz
mirror://npm/resolve-from/-/resolve-from-5.0.0.tgz
mirror://npm/wrap-ansi/-/wrap-ansi-6.2.0.tgz
mirror://npm/y18n/-/y18n-4.0.1.tgz
mirror://npm/yargs/-/yargs-15.4.1.tgz
mirror://npm/yargs-parser/-/yargs-parser-18.1.3.tgz
mirror://npm/object-inspect/-/object-inspect-1.9.0.tgz
mirror://npm/object-keys/-/object-keys-1.1.1.tgz
mirror://npm/object.assign/-/object.assign-4.1.2.tgz
mirror://npm/object.values/-/object.values-1.1.2.tgz
mirror://npm/once/-/once-1.4.0.tgz
mirror://npm/onetime/-/onetime-5.1.2.tgz
mirror://npm/optionator/-/optionator-0.9.1.tgz
mirror://npm/p-limit/-/p-limit-1.3.0.tgz
mirror://npm/p-locate/-/p-locate-2.0.0.tgz
mirror://npm/p-map/-/p-map-4.0.0.tgz
mirror://npm/p-try/-/p-try-1.0.0.tgz
mirror://npm/package-hash/-/package-hash-4.0.0.tgz
mirror://npm/package-name-regex/-/package-name-regex-1.0.8.tgz
mirror://npm/parent-module/-/parent-module-1.0.1.tgz
mirror://npm/parse-json/-/parse-json-2.2.0.tgz
mirror://npm/parse-ms/-/parse-ms-2.1.0.tgz
mirror://npm/path-exists/-/path-exists-3.0.0.tgz
mirror://npm/path-is-absolute/-/path-is-absolute-1.0.1.tgz
mirror://npm/path-key/-/path-key-3.1.1.tgz
mirror://npm/path-parse/-/path-parse-1.0.6.tgz
mirror://npm/path-type/-/path-type-2.0.0.tgz
mirror://npm/picomatch/-/picomatch-2.2.2.tgz
mirror://npm/pify/-/pify-2.3.0.tgz
mirror://npm/pinst/-/pinst-2.1.4.tgz
mirror://npm/pkg-dir/-/pkg-dir-2.0.0.tgz
mirror://npm/please-upgrade-node/-/please-upgrade-node-3.2.0.tgz
mirror://npm/prelude-ls/-/prelude-ls-1.2.1.tgz
mirror://npm/prettier/-/prettier-2.2.1.tgz
mirror://npm/pretty-bytes/-/pretty-bytes-5.5.0.tgz
mirror://npm/pretty-ms/-/pretty-ms-7.0.1.tgz
mirror://npm/process-on-spawn/-/process-on-spawn-1.0.0.tgz
mirror://npm/progress/-/progress-2.0.3.tgz
mirror://npm/pump/-/pump-3.0.0.tgz
mirror://npm/punycode/-/punycode-2.1.1.tgz
mirror://npm/querystringify/-/querystringify-2.2.0.tgz
mirror://npm/randombytes/-/randombytes-2.1.0.tgz
mirror://npm/rc/-/rc-1.2.8.tgz
mirror://npm/strip-json-comments/-/strip-json-comments-2.0.1.tgz
mirror://npm/read-pkg/-/read-pkg-2.0.0.tgz
mirror://npm/read-pkg-up/-/read-pkg-up-2.0.0.tgz
mirror://npm/readdirp/-/readdirp-3.5.0.tgz
mirror://npm/rechoir/-/rechoir-0.6.2.tgz
mirror://npm/regenerate/-/regenerate-1.4.2.tgz
mirror://npm/regenerate-unicode-properties/-/regenerate-unicode-properties-8.2.0.tgz
mirror://npm/regexpp/-/regexpp-3.1.0.tgz
mirror://npm/regexpu-core/-/regexpu-core-4.5.4.tgz
mirror://npm/regjsgen/-/regjsgen-0.5.2.tgz
mirror://npm/regjsparser/-/regjsparser-0.6.7.tgz
mirror://npm/release-zalgo/-/release-zalgo-1.0.0.tgz
mirror://npm/require-directory/-/require-directory-2.1.1.tgz
mirror://npm/require-from-string/-/require-from-string-2.0.2.tgz
mirror://npm/require-main-filename/-/require-main-filename-2.0.0.tgz
mirror://npm/require-relative/-/require-relative-0.8.7.tgz
mirror://npm/requirejs/-/requirejs-2.3.6.tgz
mirror://npm/requires-port/-/requires-port-1.0.0.tgz
mirror://npm/resolve/-/resolve-1.20.0.tgz
mirror://npm/resolve-from/-/resolve-from-4.0.0.tgz
mirror://npm/restore-cursor/-/restore-cursor-3.1.0.tgz
mirror://npm/rimraf/-/rimraf-3.0.2.tgz
mirror://npm/rollup/-/rollup-2.38.5.tgz
mirror://npm/rollup-plugin-license/-/rollup-plugin-license-2.2.0.tgz
mirror://npm/lodash/-/lodash-4.17.19.tgz
mirror://npm/rollup-plugin-string/-/rollup-plugin-string-3.0.0.tgz
mirror://npm/rollup-plugin-terser/-/rollup-plugin-terser-7.0.2.tgz
mirror://npm/commander/-/commander-2.20.3.tgz
mirror://npm/serialize-javascript/-/serialize-javascript-4.0.0.tgz
mirror://npm/terser/-/terser-5.5.1.tgz
mirror://npm/rollup-plugin-thatworks/-/rollup-plugin-thatworks-1.0.4.tgz
mirror://npm/rollup-plugin-typescript/-/rollup-plugin-typescript-1.0.1.tgz
mirror://npm/rollup-pluginutils/-/rollup-pluginutils-2.8.2.tgz
mirror://npm/estree-walker/-/estree-walker-0.6.1.tgz
mirror://npm/rxjs/-/rxjs-6.6.3.tgz
mirror://npm/tslib/-/tslib-1.14.1.tgz
mirror://npm/safe-buffer/-/safe-buffer-5.2.1.tgz
mirror://npm/sander/-/sander-0.6.0.tgz
mirror://npm/mkdirp/-/mkdirp-0.5.5.tgz
mirror://npm/rimraf/-/rimraf-2.7.1.tgz
mirror://npm/semver/-/semver-7.3.4.tgz
mirror://npm/semver-compare/-/semver-compare-1.0.0.tgz
mirror://npm/serialize-javascript/-/serialize-javascript-5.0.1.tgz
mirror://npm/set-blocking/-/set-blocking-2.0.0.tgz
mirror://npm/setimmediate-napi/-/setimmediate-napi-1.0.6.tgz
mirror://npm/shebang-command/-/shebang-command-2.0.0.tgz
mirror://npm/shebang-regex/-/shebang-regex-3.0.0.tgz
mirror://npm/shelljs/-/shelljs-0.8.4.tgz
mirror://npm/shx/-/shx-0.3.3.tgz
mirror://npm/signal-exit/-/signal-exit-3.0.3.tgz
mirror://npm/slash/-/slash-3.0.0.tgz
mirror://npm/slice-ansi/-/slice-ansi-4.0.0.tgz
mirror://npm/ansi-styles/-/ansi-styles-4.3.0.tgz
mirror://npm/color-convert/-/color-convert-2.0.1.tgz
mirror://npm/color-name/-/color-name-1.1.4.tgz
mirror://npm/sort-keys/-/sort-keys-4.2.0.tgz
mirror://npm/source-map/-/source-map-0.7.3.tgz
mirror://npm/source-map-support/-/source-map-support-0.5.19.tgz
mirror://npm/source-map/-/source-map-0.6.1.tgz
mirror://npm/sourcemap-codec/-/sourcemap-codec-1.4.8.tgz
mirror://npm/spawn-wrap/-/spawn-wrap-2.0.0.tgz
mirror://npm/spdx-compare/-/spdx-compare-1.0.0.tgz
mirror://npm/spdx-correct/-/spdx-correct-3.1.1.tgz
mirror://npm/spdx-exceptions/-/spdx-exceptions-2.3.0.tgz
mirror://npm/spdx-expression-parse/-/spdx-expression-parse-3.0.1.tgz
mirror://npm/spdx-expression-validate/-/spdx-expression-validate-2.0.0.tgz
mirror://npm/spdx-license-ids/-/spdx-license-ids-3.0.7.tgz
mirror://npm/spdx-ranges/-/spdx-ranges-2.1.1.tgz
mirror://npm/spdx-satisfies/-/spdx-satisfies-5.0.0.tgz
mirror://npm/sprintf-js/-/sprintf-js-1.0.3.tgz
mirror://npm/stream-events/-/stream-events-1.0.5.tgz
mirror://npm/string-argv/-/string-argv-0.3.1.tgz
mirror://npm/string-width/-/string-width-4.2.0.tgz
mirror://npm/string.prototype.trimend/-/string.prototype.trimend-1.0.3.tgz
mirror://npm/string.prototype.trimstart/-/string.prototype.trimstart-1.0.3.tgz
mirror://npm/stringify-object/-/stringify-object-3.3.0.tgz
mirror://npm/strip-ansi/-/strip-ansi-6.0.0.tgz
mirror://npm/strip-bom/-/strip-bom-3.0.0.tgz
mirror://npm/strip-final-newline/-/strip-final-newline-2.0.0.tgz
mirror://npm/strip-json-comments/-/strip-json-comments-3.1.1.tgz
mirror://npm/stubs/-/stubs-3.0.0.tgz
mirror://npm/supports-color/-/supports-color-5.5.0.tgz
mirror://npm/systemjs/-/systemjs-6.8.3.tgz
mirror://npm/table/-/table-6.0.7.tgz
mirror://npm/ajv/-/ajv-7.1.0.tgz
mirror://npm/json-schema-traverse/-/json-schema-traverse-1.0.0.tgz
mirror://npm/teeny-request/-/teeny-request-6.0.1.tgz
mirror://npm/terser/-/terser-5.6.0-beta.tgz
mirror://npm/commander/-/commander-2.20.3.tgz
mirror://npm/test-exclude/-/test-exclude-6.0.0.tgz
mirror://npm/text-table/-/text-table-0.2.0.tgz
mirror://npm/through/-/through-2.3.8.tgz
mirror://npm/time-zone/-/time-zone-1.0.0.tgz
mirror://npm/to-fast-properties/-/to-fast-properties-2.0.0.tgz
mirror://npm/to-regex-range/-/to-regex-range-5.0.1.tgz
mirror://npm/tsconfig-paths/-/tsconfig-paths-3.9.0.tgz
mirror://npm/tslib/-/tslib-2.1.0.tgz
mirror://npm/tslint/-/tslint-6.1.3.tgz
mirror://npm/builtin-modules/-/builtin-modules-1.1.1.tgz
mirror://npm/commander/-/commander-2.20.3.tgz
mirror://npm/diff/-/diff-4.0.2.tgz
mirror://npm/mkdirp/-/mkdirp-0.5.5.tgz
mirror://npm/semver/-/semver-5.7.1.tgz
mirror://npm/tslib/-/tslib-1.14.1.tgz
mirror://npm/tsutils/-/tsutils-2.29.0.tgz
mirror://npm/tslib/-/tslib-1.14.1.tgz
mirror://npm/type-check/-/type-check-0.4.0.tgz
mirror://npm/type-fest/-/type-fest-0.8.1.tgz
mirror://npm/typedarray-to-buffer/-/typedarray-to-buffer-3.1.5.tgz
mirror://npm/typescript/-/typescript-4.1.5.tgz
mirror://npm/uc.micro/-/uc.micro-1.0.6.tgz
mirror://npm/unicode-canonical-property-names-ecmascript/-/unicode-canonical-property-names-ecmascript-1.0.4.tgz
mirror://npm/unicode-match-property-ecmascript/-/unicode-match-property-ecmascript-1.0.4.tgz
mirror://npm/unicode-match-property-value-ecmascript/-/unicode-match-property-value-ecmascript-1.2.0.tgz
mirror://npm/unicode-property-aliases-ecmascript/-/unicode-property-aliases-ecmascript-1.1.0.tgz
mirror://npm/universalify/-/universalify-0.1.2.tgz
mirror://npm/uri-js/-/uri-js-4.4.1.tgz
mirror://npm/url-parse/-/url-parse-1.4.7.tgz
mirror://npm/urlgrey/-/urlgrey-0.4.4.tgz
mirror://npm/uuid/-/uuid-3.4.0.tgz
mirror://npm/v8-compile-cache/-/v8-compile-cache-2.2.0.tgz
mirror://npm/validate-npm-package-license/-/validate-npm-package-license-3.0.4.tgz
mirror://npm/walk-sync/-/walk-sync-2.2.0.tgz
mirror://npm/weak-napi/-/weak-napi-2.0.2.tgz
mirror://npm/which/-/which-2.0.2.tgz
mirror://npm/which-module/-/which-module-2.0.0.tgz
mirror://npm/wide-align/-/wide-align-1.1.3.tgz
mirror://npm/ansi-regex/-/ansi-regex-3.0.0.tgz
mirror://npm/is-fullwidth-code-point/-/is-fullwidth-code-point-2.0.0.tgz
mirror://npm/string-width/-/string-width-2.1.1.tgz
mirror://npm/strip-ansi/-/strip-ansi-4.0.0.tgz
mirror://npm/word-wrap/-/word-wrap-1.2.3.tgz
mirror://npm/workerpool/-/workerpool-6.1.0.tgz
mirror://npm/wrap-ansi/-/wrap-ansi-7.0.0.tgz
mirror://npm/ansi-styles/-/ansi-styles-4.3.0.tgz
mirror://npm/color-convert/-/color-convert-2.0.1.tgz
mirror://npm/color-name/-/color-name-1.1.4.tgz
mirror://npm/wrappy/-/wrappy-1.0.2.tgz
mirror://npm/write-file-atomic/-/write-file-atomic-3.0.3.tgz
mirror://npm/write-json-file/-/write-json-file-4.3.0.tgz
mirror://npm/y18n/-/y18n-5.0.5.tgz
mirror://npm/yallist/-/yallist-4.0.0.tgz
mirror://npm/yaml/-/yaml-1.10.0.tgz
mirror://npm/yargs/-/yargs-16.2.0.tgz
mirror://npm/yargs-parser/-/yargs-parser-20.2.4.tgz
mirror://npm/yargs-unparser/-/yargs-unparser-2.0.0.tgz
mirror://npm/yocto-queue/-/yocto-queue-0.1.0.tgz
"

DESCRIPTION="Next-generation ES module bundler"
HOMEPAGE="
	https://rollupjs.org/
	https://www.npmjs.com/package/rollup
"
SLOT="0"
LICENSE="MIT"
KEYWORDS="~amd64"
RDEPEND="net-libs/nodejs"
BDEPEND="net-libs/nodejs[npm]"

PATCHES=( "${FILESDIR}/${P}-is-reference.patch" )

src_unpack() {
	node-bundled_src_unpack
	unpack rollup-2.38.5.tgz
}

src_compile() {
	node-bundled_src_compile
	npm run build || die
}

S="${WORKDIR}/${MYPN}-${PV}"

src_prepare() {
#	mv "${WORKDIR}/package/dist" "${S}" || die
	#git want a git repo
	git init || die
	git config --global user.email "you@example.com" || die
	git config --global user.name "Your Name" || die
	git add . || die
	git commit -m 'init' || die

	export PATH="${WORKDIR}/package/dist/bin:${PATH}"
	node-bundled_src_prepare
}
