name: repoman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup master gentoo repository
      run: |
        ./scripts/setup-master-gentoo.sh
    - name: Setup and run Repoman
      run: |
        ./scripts/setup-and-run-repoman.sh
